### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by vladbucur2000** [spe-uob/HealthcareLake#145]
**Describe the bug**
POST requests on api_url does not work when running multiple datalakes (**healthcarelake-demo**) (did not test with running a single one so i am not sure where is the problem)

**To Reproduce**

POST requests within POSTMAN
``https://ka8fg5y9x1.execute-api.eu-west-2.amazonaws.com/demo : 403 Forbidden``
``https://ka8fg5y9x1.execute-api.eu-west-2.amazonaws.com/demo/Patient :  502 Bad Gateway``
I used a Bearer token authentication and had the token tested in the API Gateway (aws console).

**Expected behavior**
Code: 201

**Comment by vladbucur2000** [comment]
Tried running from the main repo:
<code>$ infra % terraform apply </code>
<code>var.project_name
  Enter a value: vlad
</code>
<code>
│Error: Missing required argument
│ 
│ The argument "region" is required, but was not set.
</code>

**Comment by vladbucur2000** [comment]
1. It includes the prefix "Bearer".
2. I tested it with postman 30 minutes after it was deployed.

**Comment by georgeedward2000** [comment]
I tested the API and encountered the following errors:
1. With "Bearer" prefix and "Patient" as resource:
<img width="1067" alt="Screenshot 2021-05-11 at 13 25 09" src="https://user-images.githubusercontent.com/58257818/117801208-b21e5600-b25c-11eb-9d41-592d135db1d7.png">
2. With "Bearer" prefix and wrongly spelled resource - "patient":
<img width="1069" alt="Screenshot 2021-05-11 at 13 29 25" src="https://user-images.githubusercontent.com/58257818/117801507-0f1a0c00-b25d-11eb-9f5e-e57489f04a81.png">
3. Without "Bearer" prefix:
<img width="1067" alt="Screenshot 2021-05-11 at 13 25 59" src="https://user-images.githubusercontent.com/58257818/117801563-1e995500-b25d-11eb-9275-6c6638132792.png">
4. With "Token" prefix:
<img width="1071" alt="Screenshot 2021-05-11 at 13 26 28" src="https://user-images.githubusercontent.com/58257818/117801599-2ce77100-b25d-11eb-96a9-df4a9a7f0360.png">

**Comment by georgeedward2000** [comment]
The token used is tested in API Gateway, Cognito_Authorizer to be sure it is working

**Comment by vladbucur2000** [comment]
I suggest you look at the screenshots from above to see if you see any mistakes in testing the requests to the API.

**Comment by vladbucur2000** [comment]
> I have tested it just now and it works. Full steps:
> 
> 1. `terraform apply`
> 2. `aws cognito-idp initiate-auth --auth-flow USER_PASSWORD_AUTH --auth-parameters USERNAME=testuser,PASSWORD=thepasswordthatwasgenerated, --client-id theclientidthatwasgenerated`
> 3. Header.Authorization => IdToken
> 4. POST url/dev/Patient

That is what I've did.

**Comment by joekendal** [comment]
I believe the issue could be using credentials that we gave you in the past. The deployment script generates a random password

**Comment by joekendal** [comment]
![Screenshot 2021-05-11 at 12 37 22](https://user-images.githubusercontent.com/13680617/117809099-a2e7da00-b255-11eb-9ee1-8dd8b992cc7f.png)

**Comment by joekendal** [comment]
And you have only set the header Authorization with no bearer prefix and no postman authorization flow
![](https://user-images.githubusercontent.com/13680617/117809099-a2e7da00-b255-11eb-9ee1-8dd8b992cc7f.png)

**Comment by georgeedward2000** [comment]
Yep "No Auth" was tested as well. Everything is on point.

**Comment by joekendal** [comment]
Are you testing one data lake or using the cookie cutter thing? We identified a naming conflict that would occur when applying multiple lakes to one account in https://github.com/spe-uob/HealthcareLakeAPI/blob/9e0461c4f4a3eec97cd55ec64b73a07d1d2ab026/modules/api_gateway/main.tf#L3

Multiple lakes are not officially supported by this module or the API module at this stage, anything you are working on there is experimental only. There is no official release

**Comment by vladbucur2000** [comment]
In conclusion HealthcareLakeDemo is not working?

There are too many repos and I find it very confusing. Which one is the one that we should deploy and test on it?

**Comment by armandcismaru** [comment]
You need to have the api key as a header with the name "x-api-key" and the id_token needs to be put into the Authoriztion menu having selected "Bearer Token"

**Comment by joekendal** [comment]
You can deploy this one. Please refer to the README to answer your questions about dependencies.

**Comment by joekendal** [comment]
> You need to have the api key as a header with the name "x-api-key" and the id_token needs to be put into the Authoriztion menu having selected "Bearer Token"

There is no need for api key. This has been made redundant. If you select No Auth and set Authorization header to IdToken it would work as shown in my screenshots. But Demo project is unsupported/experimental

**Comment by joekendal** [comment]
Since this issue has been resolved, the thread will be locked to prevent further confusion. Please feel free to reach out if it is still unclear
